# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secuTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_os', models.CharField(max_length=60)),
                ('compiler', models.CharField(max_length=60)),
                ('version', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=60)),
                ('port', models.CharField(max_length=20)),
                ('http_path', models.CharField(max_length=60)),
                ('invoke_format', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('target_os', models.CharField(max_length=60)),
                ('compiler', models.CharField(max_length=60)),
                ('version', models.CharField(max_length=60)),
                ('flag', models.TextField()),
            ],
        ),
    ]
