# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompilationPid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('taskid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcCodes', models.FileField(blank=True, upload_to='hellomake')),
                ('content_type', models.CharField(max_length=50)),
            ],
        ),
    ]
